//
//  UserFoodSucrCheck.swift
//  CSID_App
//
//  Created by Vince Muller on 4/22/24.
//

import UIKit

class UserFoodSucrCheck {
    
    var sugarIngredients: [String] = [
        "organic hydrogenated starch hydrolysates",
        "organic hfcs (high-fructose corn syrup)",
        "organic free-flowing brown sugars",
        "hydrogenated starch hydrolysates",
        "organic high fructose corn syrup",
        "hfcs (high-fructose corn syrup)",
        "organic brown rice syrup solids",
        "organic fruit juice concentrate",
        "organic dehydrated cane juice",
        "organic evaporated cane juice",
        "organic confectioner's sugar",
        "organic cane juice crystals",
        "organic coconut palm sugar",
        "organic monk fruit extract",
        "free-flowing brown sugars",
        "organic barley malt syrup",
        "organic corn syrup solids",
        "high fructose corn syrup",
        "organic brown rice syrup",
        "organic refiner's syrup",
        "organic turbinado sugar",
        "brown rice syrup solids",
        "fruit juice concentrate",
        "organic barbados sugar",
        "organic buttered syrup",
        "organic cemerara sugar",
        "organic powdered sugar",
        "organic corn sweetener",
        "organic glucose solids",
        "dehydrated cane juice",
        "evaporated cane juice",
        "organic coconut sugar",
        "organic sorghum Syrup",
        "organic sweet sorghum",
        "organic sugar alcohol",
        "confectioner's sugar",
        "organic castor sugar",
        "organic golden sugar",
        "organic golden syrup",
        "organic invert sugar",
        "organic yellow sugar",
        "organic agave nectar",
        "organic maltodextrin",
        "cane juice crystals",
        "organic brown sugar",
        "organic carob syrup",
        "organic icing sugar",
        "organic maple syrup",
        "organic agave syrup",
        "organic barley malt",
        "organic fruit juice",
        "organic grape sugar",
        "coconut palm sugar",
        "organic beet sugar",
        "organic cane juice",
        "organic cane sugar",
        "organic cane syrup",
        "organic palm sugar",
        "organic saccharose",
        "monk fruit extract",
        "organic date sugar",
        "organic malt syrup",
        "organic rice syrup",
        "organic corn syrup",
        "organic erythritol",
        "organic monk fruit",
        "barley malt syrup",
        "organic muscovado",
        "organic raw sugar",
        "corn syrup solids",
        "organic molasses",
        "brown rice syrup",
        "organic dextrose",
        "organic fructose",
        "organic maltitol",
        "organic mannitol",
        "organic sorbitol",
        "refiner's syrup",
        "turbinado sugar",
        "organic caramel",
        "organic panocha",
        "organic sucrose",
        "organic treacle",
        "organic dextrin",
        "organic glucose",
        "organic maltose",
        "organic mannose",
        "organic xylitol",
        "organic isomalt",
        "buttered syrup",
        "cemerara sugar",
        "powdered sugar",
        "corn sweetener",
        "glucose solids",
        "organic maltol",
        "barbados sugar",
        "coconut sugar",
        "sorghum Syrup",
        "sweet sorghum",
        "organic sugar",
        "organic syrup",
        "organic honey",
        "castor sugar",
        "golden sugar",
        "golden syrup",
        "invert sugar",
        "yellow sugar",
        "sugar alcohol",
        "agave nectar",
        "maltodextrin",
        "brown sugar",
        "carob syrup",
        "icing sugar",
        "maple syrup",
        "agave syrup",
        "barley malt",
        "fruit juice",
        "grape sugar",
        "beet sugar",
        "cane juice",
        "cane sugar",
        "cane syrup",
        "palm sugar",
        "saccharose",
        "date sugar",
        "malt syrup",
        "rice syrup",
        "corn syrup",
        "erythritol",
        "monk fruit",
        "muscovado",
        "raw sugar",
        "molasses",
        "dextrose",
        "fructose",
        "maltitol",
        "mannitol",
        "sorbitol",
        "caramel",
        "panocha",
        "sucrose",
        "treacle",
        "dextrin",
        "glucose",
        "maltose",
        "mannose",
        "xylitol",
        "isomalt",
        "maltol",
        "sugar",
        "syrup",
        "honey"
    ]
    
    var replacedSugarIngredients: [String] = [
        "O300",
        "O299",
        "S298",
        "O297",
        "O296",
        "O295",
        "O294",
        "O293",
        "S292",
        "S291",
        "S290",
        "S289",
        "S288",
        "O287",
        "S286",
        "S285",
        "O284",
        "O283",
        "O282",
        "S281",
        "S280",
        "O279",
        "O278",
        "S277",
        "S276",
        "S275",
        "S274",
        "O273",
        "O272",
        "S271",
        "S270",
        "S269",
        "S268",
        "S267",
        "O266",
        "S265",
        "S264",
        "S263",
        "S262",
        "S261",
        "S260",
        "O259",
        "O258",
        "S257",
        "S256",
        "S255",
        "S254",
        "S253",
        "O252",
        "O251",
        "O250",
        "O249",
        "S248",
        "S247",
        "S246",
        "S245",
        "S244",
        "S243",
        "S242",
        "O241",
        "O240",
        "O239",
        "O238",
        "O237",
        "O236",
        "O235",
        "S234",
        "S233",
        "S232",
        "O231",
        "S230",
        "O229",
        "O228",
        "O227",
        "O226",
        "O225",
        "O224",
        "S223",
        "S222",
        "S221",
        "S220",
        "S219",
        "S218",
        "O217",
        "O216",
        "O215",
        "O214",
        "O213",
        "O212",
        "S211",
        "S210",
        "S209",
        "O208",
        "O207",
        "O206",
        "S205",
        "S204",
        "S203",
        "S202",
        "S201",
        "S200",
        "O199",
        "S198",
        "S197",
        "S196",
        "S195",
        "S194",
        "O193",
        "O192",
        "O191",
        "S190",
        "S189",
        "S188",
        "S187",
        "O186",
        "O185",
        "O184",
        "O183",
        "S182",
        "S181",
        "S180",
        "S179",
        "S178",
        "S177",
        "O176",
        "O175",
        "O174",
        "O173",
        "O172",
        "O171",
        "S170",
        "S169",
        "S168",
        "O167",
        "O166",
        "O165",
        "O164",
        "O163",
        "S162",
        "S161",
        "S160",
        "S159",
        "O158",
        "O157",
        "O156",
        "O155",
        "O154",
        "O153",
        "O152",
        "S151",
        "S150",
        "O149"
    ]
    
    func makingIngredientsUnique(originalIngredients: String) -> String {
           let productIngredients = originalIngredients.lowercased().replacingOccurrences(of: "sugar free", with: "")
           var replacedProductIngredients = productIngredients
           var x: Int = 0
           
        while x <  sugarIngredients.count {
               replacedProductIngredients = replacedProductIngredients.replacingOccurrences(of: sugarIngredients[x], with: replacedSugarIngredients[x])
               x = x + 1
           }
           
           x = 0
        
           return replacedProductIngredients
       }
       
       func getSugarIngredients(productIngredients: String) -> [[String]] {
           var returnedIngredients: [[String]] = [[],[]]
           print(productIngredients)
           var x: Int = 0
           
           while x < replacedSugarIngredients.count {
               if productIngredients.contains(replacedSugarIngredients[x]) {
                   if replacedSugarIngredients[x].contains("S") {
                       returnedIngredients[0].append(sugarIngredients[x])
                   } else {
                       returnedIngredients[1].append(sugarIngredients[x])
                   }
               }
               x = x + 1
           }
           
           return returnedIngredients
       }
       
}
